### ISSUE TITLE
native crystal

### ISSUE THREAD

**Issue by q9f** [SushiChain/crystal-ecdsa#4]
hi there, have you ever considered porting https://github.com/insanum/ecies to native crystal?

I already wrote https://github.com/q9f/secp256k1.cr in crystal and now looking for an ECIES library to implement RLPx. Curious if you think this is feasible?

**Comment by kingsleyh** [comment]
Hi - I think it’s feasible. We did originally have native crystal code for some of these but switched to OpenSSL for cross platform compatibility. We found that different languages, libraries and platforms had different implementations that produced different results which was problematic for our use cases

**Comment by kingsleyh** [comment]
I've merged your pull request now - so using your lib. Awesome work :)
